# Generated by Django 5.1 on 2025-01-25 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology_app', '0002_zodiacsign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horoscope',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='title',
        ),
        migrations.AddField(
            model_name='horoscope',
            name='date',
            field=models.DateField(default='2025-01-25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='family_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='health_rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='love_rating',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='lucky_color',
            field=models.CharField(default='Red', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='lucky_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='married_life_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='occupation_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='remedy',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='wealth_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horoscope',
            name='zodiac_sign',
            field=models.ForeignKey(default='libra', on_delete=django.db.models.deletion.CASCADE, related_name='horoscopes', to='astrology_app.zodiacsign'),
            preserve_default=False,
        ),
    ]
