# Generated by Django 5.1 on 2025-01-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology_app', '0004_alter_horoscope_family_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horoscope',
            name='married_life_rating',
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='zodiac_sign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='astrology_app.zodiacsign'),
        ),
    ]
